/*
 *  Nama : Tassyakur Pasya
 *  Kelas : IF01
 *  NIM : 10118009
 *  Deskripsi Program : 
 */
package pbo.upil.views;

/**
 *
 * @author Achapasya2109
 */
public class KartuKandidat extends javax.swing.JPanel {

    /**
     * Creates new form KartuKandidat
     */
    public KartuKandidat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto_kandidat1 = new javax.swing.JTextField();
        no_kandidat1 = new javax.swing.JTextField();
        nama_kandidat1 = new javax.swing.JTextField();
        visi_kandidat1 = new javax.swing.JTextField();
        misi_kandidat1 = new javax.swing.JTextField();
        kandidat1 = new javax.swing.JRadioButton();

        foto_kandidat1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        foto_kandidat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        foto_kandidat1.setText("FOTO 1");

        no_kandidat1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        no_kandidat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no_kandidat1.setText("1");

        nama_kandidat1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        nama_kandidat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama_kandidat1.setText("NAMA KAN 01");

        visi_kandidat1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        visi_kandidat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        visi_kandidat1.setText("VISI KAN 01");

        misi_kandidat1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        misi_kandidat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        misi_kandidat1.setText("MISI KAN 01");

        kandidat1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foto_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(no_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nama_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(visi_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(misi_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(foto_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(no_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(nama_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(visi_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(misi_kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kandidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField foto_kandidat1;
    private javax.swing.JRadioButton kandidat1;
    private javax.swing.JTextField misi_kandidat1;
    private javax.swing.JTextField nama_kandidat1;
    private javax.swing.JTextField no_kandidat1;
    private javax.swing.JTextField visi_kandidat1;
    // End of variables declaration//GEN-END:variables
}
