/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo.upil.views;

import java.beans.PropertyChangeEvent;
import pbo.upil.controllers.KandidatController;

/**
 *
 * @author nurhamidan
 */
public class TambahKandidatPanel extends AbstractView {

    /**
     * Creates new form TambahKandidatPanel
     */
    
    private final KandidatController kandidatController;
    
    public TambahKandidatPanel(KandidatController kandidatController) {
        this.kandidatController = kandidatController;
        kandidatController.addView(this);
        initComponents();
    }
    
    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(KandidatController.ELEMENT_TEXT_PROPERTY)) {
            String newStringValue = evt.getNewValue().toString();
            if (!txtNomorKandidat.getText().equals(newStringValue)) {
                txtNomorKandidat.setText(newStringValue);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtNomorKandidat2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnOk2 = new javax.swing.JButton();
        btnMasuk5 = new javax.swing.JButton();
        btnMasuk6 = new javax.swing.JButton();
        txtNamaKandidat2 = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(250, 248, 240));

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tambah Kandidat");

        jSeparator5.setForeground(new java.awt.Color(49, 173, 226));

        txtNomorKandidat2.setBackground(new java.awt.Color(250, 248, 240));
        txtNomorKandidat2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 10)); // NOI18N
        txtNomorKandidat2.setForeground(new java.awt.Color(49, 173, 226));
        txtNomorKandidat2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomorKandidat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomorKandidat2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(6, 62, 97));
        jLabel8.setText("Nama Kandidat");

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(6, 62, 97));
        jLabel9.setText("Nomor Kandidat");

        jSeparator6.setForeground(new java.awt.Color(49, 173, 226));

        btnOk2.setBackground(new java.awt.Color(49, 173, 226));
        btnOk2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnOk2.setForeground(new java.awt.Color(250, 248, 240));
        btnOk2.setText("Ok");
        btnOk2.setAlignmentY(1.0F);
        btnOk2.setFocusable(false);
        btnOk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOk2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOk2MouseExited(evt);
            }
        });
        btnOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk2ActionPerformed(evt);
            }
        });

        btnMasuk5.setBackground(new java.awt.Color(49, 173, 226));
        btnMasuk5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnMasuk5.setForeground(new java.awt.Color(250, 248, 240));
        btnMasuk5.setText("Reset");
        btnMasuk5.setAlignmentY(1.0F);
        btnMasuk5.setFocusable(false);
        btnMasuk5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasuk5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasuk5MouseExited(evt);
            }
        });
        btnMasuk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasuk5ActionPerformed(evt);
            }
        });

        btnMasuk6.setBackground(new java.awt.Color(49, 173, 226));
        btnMasuk6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnMasuk6.setForeground(new java.awt.Color(250, 248, 240));
        btnMasuk6.setText("Batal");
        btnMasuk6.setAlignmentY(1.0F);
        btnMasuk6.setFocusable(false);
        btnMasuk6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasuk6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasuk6MouseExited(evt);
            }
        });
        btnMasuk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasuk6ActionPerformed(evt);
            }
        });

        txtNamaKandidat2.setBackground(new java.awt.Color(250, 248, 240));
        txtNamaKandidat2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 10)); // NOI18N
        txtNamaKandidat2.setForeground(new java.awt.Color(49, 173, 226));
        txtNamaKandidat2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNamaKandidat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKandidat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNamaKandidat2)
                    .addComponent(txtNomorKandidat2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMasuk5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMasuk6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomorKandidat2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaKandidat2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk2)
                    .addComponent(btnMasuk6)
                    .addComponent(btnMasuk5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomorKandidat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorKandidat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorKandidat2ActionPerformed

    private void btnOk2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOk2MouseEntered
        // TODO add your handling code here:
        btnOk.setBackground(new java.awt.Color(6,62,97));
    }//GEN-LAST:event_btnOk2MouseEntered

    private void btnOk2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOk2MouseExited
        // TODO add your handling code here:
        btnOk.setBackground(new java.awt.Color(49,173,226));
    }//GEN-LAST:event_btnOk2MouseExited

    private void btnOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk2ActionPerformed
        // TODO add your handling code here:
        //TampilanAdmin.tblKandidatModel.addRow(new Object[]{"1", "Udin"});
        //this.setVisible(false);
        //ta.setVisible(true);
        //tambahKandidatController.simpanData(new TampilanAdmin());
    }//GEN-LAST:event_btnOk2ActionPerformed

    private void btnMasuk5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasuk5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasuk5MouseEntered

    private void btnMasuk5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasuk5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasuk5MouseExited

    private void btnMasuk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasuk5ActionPerformed
        kandidatController.reset();
    }//GEN-LAST:event_btnMasuk5ActionPerformed

    private void btnMasuk6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasuk6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasuk6MouseEntered

    private void btnMasuk6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasuk6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasuk6MouseExited

    private void btnMasuk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasuk6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasuk6ActionPerformed

    private void txtNamaKandidat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKandidat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKandidat2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk1;
    private javax.swing.JButton btnMasuk2;
    private javax.swing.JButton btnMasuk3;
    private javax.swing.JButton btnMasuk4;
    private javax.swing.JButton btnMasuk5;
    private javax.swing.JButton btnMasuk6;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOk1;
    private javax.swing.JButton btnOk2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtNamaKandidat;
    private javax.swing.JTextField txtNamaKandidat1;
    private javax.swing.JTextField txtNamaKandidat2;
    private javax.swing.JTextField txtNomorKandidat;
    private javax.swing.JTextField txtNomorKandidat1;
    private javax.swing.JTextField txtNomorKandidat2;
    // End of variables declaration//GEN-END:variables
}
